name: push-html
description: push html file to USER.github.io
inputs:
  src:
    required: true
  token:
    required: true
  user:
    default: ${{github.repository_owner}}
  repo:
    default: ${{github.repository_owner}}.github.io
  dst:
    default: .
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{inputs.token}}
        repository: ${{inputs.user}}/${{inputs.repo}}
        path: ${{inputs.repo}}
    - name: copy
      shell: bash
      run: |
        set -xe
        user=${{github.repository_owner}}
        email=$(git log -n1 --author="$user" --format=format:%ae)
        git config user.name "$user[sync]"
        git config user.email "${email:-actions@github.com}"
        rsync -avR ${{inputs.src}} ${{inputs.repo}}/${{inputs.dst}}
        cd ${{inputs.repo}}
        git add ${{inputs.dst}}
        git diff --cached --quiet ||
                git -c user.name="$user" -c user.email="$email" commit \
                        -m 'updating ${{inputs.src}}'
        git push

